config/routes.rb
Rails.application.routes.draw do
  devise_for :clients

  devise_for :users
  devise_for :admins
  root 'home#index'

  namespace :admin do
    root 'home#index'
    resources :events do
      resources :questions do
        member do
          put "like", to: "questions#upvote"
        end
      end
    end
  end
  resources :events do
    resources :questions do
      member do
        put "like", to: "questions#upvote"
      end
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  acts_as_votable

  validates :content, presence: true

  def score
    self.get_upvotes.size
  end
end

app/models/session.rb
class Session < ActiveRecord::Base
  acts_as_voter
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  has_many :questions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class BaseController < ActionController::Base
  before_action :authenticate_admin!
  layout 'admin'
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  before_action :authenticate_admin!
  before_action :find_event, only: [:show, :edit, :destroy, :update]

  def index
    @events = Event.all
  end

  def new
    @event = current_admin.events.build
  end

  def show
  end

  def create
    @event = current_admin.events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @event.destroy
    redirect_to admin_root_path
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description)
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  before_action :authenticate_admin!

  def index
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :authenticate_admin!

  before_action :find_event, only: [:create, :edit, :update, :destroy, :upvote]
  before_action :find_question, only: [:edit, :update, :destroy, :upvote]

  def create
    @question = @event.questions.create(question_params)
    @question.user_id = current_user.id if current_user
    if @question.save
      redirect_to event_path(@event)
    else
      render 'events/show'
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    redirect_to event_path(@event)
  end

  def upvote
    @question.upvote_by current_user
    redirect_to event_path(@event)
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_question
    @question = @event.questions.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_event, only: [:show, :edit, :destroy, :update]

  def index
    @events = Event.where(user_id: current_user)
  end

  def new
    @event = current_user.events.build
  end

  def show
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event
      flash[:notice] = "Event was successfully created!"
    else
      render 'new'
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event
      flash[:notice] = "Event was successfully updated!"
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @event.destroy
    redirect_to root_path
    flash[:notice] = "Event was successfully deleted!"
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_event, only: [:create, :edit, :update, :destroy, :upvote]
  before_action :find_question, only: [:edit, :update, :destroy, :upvote]

  def create
    @question = @event.questions.create(question_params)
    @question.user_id = current_user.id if current_user
    @question.save
    respond_to do |format|
      format.html {
        if @question.save
    			redirect_to event_path(@event)
    		else
    			render 'new'
    		end
      }
      format.js { render layout: false } # render questions/create.js.erb
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      flash[:alert] = "Question successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    if @question.user != current_user
      flash[:notice] = "Can't delete this question."
    else
      @question.destroy
      respond_to do |format|
        format.html { redirect_to event_path(@event) }
        format.js { render layout: false } # JavaScript response
      end
    end
  end

  def upvote
    session[:voting_id] = request.remote_ip
    voter = Session.find_or_create_by(ip: session[:voting_id])
    @question.upvote_by voter
    redirect_to event_path(@event)
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_question
    @question = @event.questions.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/events/_form.html.haml
= simple_form_for [:admin, @event] do |f|
  = f.input :title, label: 'Title of the event'
  = f.input :description, label: 'Events description'
  = f.submit

app/views/admin/events/edit.haml
%h1 Edit event
= render 'form'

app/views/admin/events/index.html.haml
%h1 All events:
- @events.each do |event|
  %p= link_to event.title, [:admin, event], class: 'button'
= link_to "Create event", new_admin_event_path, class: 'buttons'

app/views/admin/events/new.html.haml
%h1 Create new event
=render 'form'

app/views/admin/events/show.haml
.row
  .col-lg-2
  .col-lg-8
    %section.title_section
      %h1.title
        = @event.title
      %p.date
        Submitted #{time_ago_in_words(@event.created_at)} ago
        = link_to 'Edit', edit_admin_event_path, class: 'buttons'
        = link_to 'Delete', event_path, method: :delete, data: {confirm: 'Are you sure?'}, class: 'buttons'
        = link_to 'View description', '#', id: 'description-link', class: 'buttons'
      %br
      %p#description
        = @event.description

    %section#question_section
      %h1.event_count
        = @event.questions.count
        ='Question'.pluralize(@event.questions.count)
      #questions
        = render @event.questions

      #question-form
        %h1 Submit a question:
        = render 'questions/form'

    = link_to "Back", admin_root_path, class: 'btn btn-primary'
    = link_to "Edit", edit_admin_event_path, class: 'btn btn-primary'
    = link_to "Delete", event_path, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger'

app/views/admin/home/index.haml
.top_text
  %h1 Welcome to our Q&A platform!

app/views/admin/questions/_form.haml
= simple_form_for [@event, @event.questions.build], remote: true do |f|
	= f.input :content, label: 'Your question:', id: 'question_content'
	= f.submit class: 'submit_btn'

app/views/admin/questions/_question.haml
#question_container
	%p
		= question.content

		= link_to "", like_admin_event_question_path(@event, question), method: :put,class:'glyphicon glyphicon-thumbs-up'
		= question.score
		= 'Vote'.pluralize(question.score)

	= link_to "Edit", edit_admin_event_question_path(question.event, question), class: "buttons"
	= link_to "Delete", [question.event, question], method: :delete, data: {confirm: "Are you sure?"}, remote: true, class: 'delete-question buttons'

app/views/admin/questions/edit.haml
%h1 Edit question:

=simple_form_for ([@event, @question]) do |f|
	= f.input :content
	= f.submit

app/views/events/_form.haml
= simple_form_for @event do |f|
  = f.input :title, label: 'Title'
  = f.input :description, label: 'Description'
  = f.submit
.links
  = link_to "Cancel", events_path  

app/views/events/_form.html.haml
= simple_form_for @event do |f|
  = f.input :title, label: 'Title'
  = f.input :description, label: 'Description'
  = f.submit

app/views/events/edit.haml
.container
  #edit_event
    %h1 Edit event
    = render 'form'

app/views/events/index.haml
.container
  %section#index_events
    %h1 EVENTS
    - @events.each do |event|
      .index_row.clearfix
        %h2.event_title= link_to event.title, event
    .links
      = link_to "Create Event", new_event_path

app/views/events/index.html.haml
.container
  %section#index_events
    %h1 EVENTS
    - @events.each do |event|
      .index_row.clearfix
        %h2.event_title= link_to event.title, event
    .links
      = link_to "Create Event", new_event_path

app/views/events/new.haml
.container
  #event_form
    %h1 New Event
    =render 'form'

app/views/events/new.html.haml
.container
  #event_form
    %h1 New Event
    =render 'form'

app/views/events/show.haml
.container
  %section.title_section
    %h1.title
      = @event.title
    .date
      Submitted #{time_ago_in_words(@event.created_at)} ago
    .links
      = link_to 'Edit', edit_event_path
      = link_to 'Delete', event_path, method: :delete, data: {confirm: 'Are you sure?'}
      = link_to 'View description', '#', id: 'description-link'
    %br
    %p#description
      = @event.description

  %section#question_section
    %h1.event_count
      = @event.questions.count
      ='Question'.pluralize(@event.questions.count)
    #questions
      = render @event.questions.sort_by {|n| n.score}.reverse

    #question-form
      %h1 New Question
      = render 'questions/form'



-# comment

app/views/home/index.haml
.container
  .top_text
    %h1 Welcome to our Q&A platform!

app/views/layouts/admin.haml
!!!
%html
  %head
    %title QAndA
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:400,700", :rel => "stylesheet", :type => "text/css"}/
  %body
    %header#top_header.clearfix
      .wrapper
        .logo
          = link_to "Q&A platform", admin_root_path
        %nav#main_nav
          = link_to 'My Events', admin_events_path
          = link_to 'New Event', new_admin_event_path
          = link_to 'Sign Out Admin', destroy_admin_session_path, method: :delete
    .wrapper
      = yield
      %p.notice= notice
      %p.alert= alert
      %p You logged in as:
      = current_admin.email

app/views/layouts/application.haml
!!!
%html
  %head
    %title QAndA
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:400,700", :rel => "stylesheet", :type => "text/css"}/
  %body
    %header#top_header.clearfix
      .wrapper
        .logo
          = link_to "Q&A platform", root_path
        %nav#main_nav
          -if user_signed_in?
            = link_to 'My Events', events_path
            = link_to 'New Event', new_event_path
            = link_to 'Sign Out', destroy_user_session_path, method: :delete
          -else
            = link_to 'Sign Up', new_user_registration_path, class: 'sign_up'
            = link_to 'Log In', new_user_session_path
            -# = link_to 'Admin Log In', new_admin_session_path
    - if notice
      #notice_wrapper
        %p.notice= notice
    - elsif alert
      #notice_wrapper
        %p.alert= alert
    .wrapper
      = yield

app/views/questions/_form.haml
= simple_form_for [@event, @event.questions.build], remote: true do |f|
	= f.input :content, label: 'Question', id: 'question_content'
	= f.submit

app/views/questions/_question.haml
#question_container
	%p
		= question.content
		= question.user_id.inspect

	#votes
		= link_to "", like_event_question_path(@event, question), method: :put,class:'glyphicon glyphicon-thumbs-up'
		= question.score
		= 'Vote'.pluralize(question.score)


	.links
		= link_to "Edit", edit_event_question_path(question.event, question), class: "button"
		= link_to "Delete", [question.event, question], method: :delete, data: {confirm: "Are you sure?"}, remote: true, id: 'delete_question'

app/views/questions/create.js.erb
$('#questions').append("<%= j render partial: @question %>");
$('#question_content').val('');
// question_content is an id created by rails

app/views/questions/destroy.js.erb
$('#delete_question').bind('ajax:success', function() {
        $(this).closest('#question_container').fadeOut();
});

app/views/questions/edit.haml
.container
	#edit_question
		%h1 Edit Question

		=simple_form_for ([@event, @question]) do |f|
			= f.input :content
			= f.submit